version: 2.1

jobs:
  johnny-cache:
    resource_class: small
    docker:
      - image: cimg/base:current
    parallelism: 3
    steps:
      - restore_cache:
          keys:
            - johhny-cache-{{ arch }}-{{ .Branch }}-
            - johhny-cache-{{ arch }}-
      - run:
          name: sleep based on node index
          command: |
            sleep $(((CIRCLE_NODE_INDEX+1) * 10))
      - run:
          name: check dependency
          command: |
            cat dep/check.txt || true
      - run:
          name: create or update dependency
          command: |
            mkdir dep
            echo "This is created by ${CIRCLE_BUILD_URL} on Node ${CIRCLE_NODE_INDEX}" > dep/check.txt
      - save_cache:
          key: johhny-cache-{{ arch }}-{{ .Branch }}-{{ checksum "dep/check.txt" }}
          paths:
            -  dep
workflows:
  cache-is-king:
    jobs:
      - johnny-cache
